// src/components/hero-featured.tsx
import { usePages } from '@rspress/core/runtime'
import { collectPosts } from '@/lib/posts'

export default function HeroFeatured() {
  const { pages } = usePages()
  const featured = collectPosts(pages)[0]

  if (!featured) {
    return null
  }

  return (
    <a href={featured.url} className="home-shell -mt-2 block no-underline">
      <div className="hero-box group cursor-pointer">
        <div className="max-w-3xl">
          <span className="page-kicker">Latest</span>
          <h1 className="post-card-title mt-4 text-2xl md:text-3xl group-hover:!text-[var(--accent)]">
            {featured.title}
          </h1>
          <div className="post-card-meta mt-3">{featured.date}</div>
          {featured.description ? (
            <p className="post-card-desc mt-4 text-base leading-8 md:text-lg">
              {featured.description}
            </p>
          ) : null}
          {featured.tags.length ? (
            <div className="mt-5 flex flex-wrap gap-2">
              {featured.tags.map(tag => (
                <span key={tag} className="tag-chip">
                  {tag}
                </span>
              ))}
            </div>
          ) : null}
          <span className="mt-6 inline-block text-sm font-medium text-[var(--accent)]">
            阅读全文 →
          </span>
        </div>
      </div>
    </a>
  )
}

// docs/.vitepress/theme/components/HeroFeatured.vue
<script setup lang="ts">
import { data as posts } from '../../data/posts.data'

const featured = posts[0]
</script>

<template>
  <a
    v-if="featured"
    :href="featured.url"
    class="home-shell -mt-2 block no-underline"
  >
    <div class="hero-box group cursor-pointer">
      <div class="max-w-3xl">
        <span class="page-kicker">Latest</span>
        <h1 class="post-card-title mt-4 text-2xl md:text-3xl group-hover:!text-[var(--accent)]">
          {{ featured.title }}
        </h1>
        <div class="post-card-meta mt-3">{{ featured.date }}</div>
        <p v-if="featured.description" class="post-card-desc mt-4 text-base md:text-lg leading-8">
          {{ featured.description }}
        </p>
        <div v-if="featured.tags?.length" class="mt-5 flex flex-wrap gap-2">
          <span v-for="tag in featured.tags" :key="tag" class="tag-chip">
            {{ tag }}
          </span>
        </div>
        <span class="mt-6 inline-block text-sm font-medium" style="color: var(--accent)">
          阅读全文 →
        </span>
      </div>
    </div>
  </a>
</template>
